### ISSUE TITLE
Where is the UiSystemDemo.cpp file?

### ISSUE THREAD

**Issue by DVDTSB** [bkshepherd/DaisySeedProjects#16]
In `guitar_pedal_ui.cpp` it is written:

```c++
// These will be called from the UI system. @see InitUi() in UiSystemDemo.cpp
void FlushCanvas(const UiCanvasDescriptor& canvasDescriptor)
{
    ...
}
```

I can't seem to find the file in the repo.

**Comment by bkshepherd** [comment]
Sorry, that's a stray comment from where I copied that function from out of the Electrosmith Lib Daisy Examples.     There is an InitUI() function in guitar_pedal_ui.cpp that does the same init.  You can see it here:

![image](https://github.com/bkshepherd/DaisySeedProjects/assets/19240460/9e8c5b99-025f-414a-9b42-54140f99425c)
